# Basic
title: FELICS
subtitle: 万物之中,希望至美,至美之物,永不凋零
welcome_message: 
description: Life@Shanghai Work@WANDA
creator: <a href="https://geekr.me">@GEEKR</a>

url: "http://felics.geekr.me"

permalink: /:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: gray-lightest

# The blog button should not be removed.
blog_button:
    title: BLOG
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: GEEKR, description: 人工智能聚合阅读, url: 'https://geekr.me'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: felics
    # duoshuo: 
    
# Social
social:
    weibo: princecharming
    github: felics

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
