# Basic
title: Trendy Man
subtitle: a backend developer
welcome_message: Life@Shanghai Work@Meituan
description: stick to truth, stick to target
creator: <a href="https://cqcxy.com">@trendystar</a>

url: "https://trendystar.github.io"

permalink: /:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: gray-lightest

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
#nav:
#    - {title: 简历, description: 我的简历, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: felics
    # duoshuo: 
    
# Social
social:
    weibo: princecharming
    github: trendystar
    twitter: huangthink
    mail: huangthink@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
